[package]
name = "relay-tendermint"
version = "0.1.0"
edition = "2021"

[dependencies]
tendermint      = { version = "=0.23.7" }
tendermint-rpc  = { version = "=0.23.7", features = ["http-client", "websocket-client"] }
tendermint-light-client-verifier = { version = "=0.23.7", default-features = false }
prost-types = { version = "0.10", default-features = false }
ibc = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
ibc-relayer = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed" }
ibc-proto = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
anyhow = { version = "1.0.56" }
tokio = { version = "1.0" }
lcp-types = { path = "../../types" }